apiVersion: config.projectsveltos.io/v1beta1
kind: ClusterPromotion
metadata:
  name: podinfo-rollout
spec:
  profileSpec:
    syncMode: Continuous
    helmCharts:
    - repositoryURL: https://stefanprodan.github.io/podinfo
      repositoryName: podinfo
      chartName: podinfo/podinfo
      chartVersion: 6.12.0
      releaseName: podinfo
      releaseNamespace: podinfo
      helmChartAction: Install
      values: |
        replicaCount: 2
        ui:
          color: "#34A853"
          message: "Progressive rollout v2"
    validateHealths:
    - name: podinfo-deployment-health
      featureID: Helm
      group: "apps"
      version: "v1"
      kind: "Deployment"
      namespace: podinfo
      script: |
        function evaluate()
          hs = {}
          hs.healthy = false
          hs.message = "available replicas not matching requested replicas"
          if obj.status ~= nil then
            if obj.status.availableReplicas ~= nil then
              if obj.status.availableReplicas == obj.spec.replicas then
                hs.healthy = true
                hs.message = "all replicas available"
              end
            end
          end
          return hs
        end
  stages:
  - name: dev
    clusterSelector:
      matchLabels:
        env: dev
    trigger:
      auto:
        delay: 2m
  - name: staging
    clusterSelector:
      matchLabels:
        env: staging
    trigger:
      auto:
        delay: 2m
