apiVersion: config.projectsveltos.io/v1beta1
kind: ClusterProfile
metadata:
  name: podinfo-staging
spec:
  clusterSelector:
    matchLabels:
      env: staging
  syncMode: Continuous
  helmCharts:
    - repositoryURL: https://stefanprodan.github.io/podinfo
      repositoryName: podinfo
      chartName: podinfo/podinfo
      chartVersion: 6.12.0
      releaseName: podinfo
      releaseNamespace: podinfo
      helmChartAction: Install
      values: |
        replicaCount: 2
        ui:
          color: "4285F4"
          message: "Running on STAGING"